on:
  push:
    branches:
      - dev
name: 🚀 Deploy website on push to dev branch
jobs:
  web-deploy:
    name: 🎉 Deploy to staging env
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 147.79.103.53
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./
